[extend]
useDefault = true

[allowlist]
paths = [
    '''scripts/replace_rdm_url\.py''',
    '''.*\.md'''
]

[[rules]]
id = "email-address"
description = "Detects email addresses"
regex = '''[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}'''
[rules.allowlist]
regexes = [
    '''.*@test\.nii\.ac\.jp''',
    '''.*@example\.com'''
]

[[rules]]
id = "rdm-nii-url"
description = "Detects rdm.nii.ac.jp URLs"
regex = '''https?://[^/]*rdm\.nii\.ac\.jp[^\s'"]*'''

[[rules]]
id = "ipv4-address"
description = "Detects IPv4 addresses"
regex = '''\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b'''