repos:
  # Clean notebook metadata
  - repo: local
    hooks:
      - id: clean-notebook-metadata
        name: Clean notebook metadata
        entry: python scripts/clean_notebook_metadata.py
        language: system
        files: '\.ipynb$'
        pass_filenames: true

  # Detect secrets
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.21.2
    hooks:
      - id: gitleaks
        name: Detect secrets
        entry: gitleaks protect --verbose --redact --staged --config .gitleaks.toml
        pass_filenames: false